<a href="https://colab.research.google.com/github/Warabhi/Letsupgrade/blob/main/Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
import numpy as np

Q1

In [2]:
arr = np.arange(start=2, stop=50, step=3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


Q2

In [5]:
l1 = list(input())
l2 = list(input())
arr1 = np.array(l1)
arr2 = np.array(l2)
arr = np.concatenate((arr1, arr2))
print(np.sort(arr))

74120
89635
['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']


Q3

In [6]:
# Creating array object
arr = np.array( [[ 1, 2, 3],[ 4, 2, 5]] )
print(arr.ndim)
print(arr.shape)

2
(2, 3)


Q4

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
print(a)
a2 = a[np.newaxis, :]
print(a2.shape)
print(a2)

(6,)
[1 2 3 4 5 6]
(1, 6)
[[1 2 3 4 5 6]]


Q5

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print('Horizontal Append:', np.hstack((a, b)))
print('Vertical Append:', np.vstack((a, b)))

Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]


Q6

In [12]:
arr = np.array([1, 1, 2, 3, 4, 4, 1])

(unique, counts) = np.unique(arr, return_counts=True)
frequencies = np.asarray((unique, counts)).T

print(frequencies)

[[1 3]
 [2 1]
 [3 1]
 [4 2]]
